### ISSUE TITLE
Fantasy: Add new Role and new Features for the NFL Fantasy game

### ISSUE THREAD

**Issue by KDanny41** [gobo7793/Geckarbot#17]
This Feature Request has two parts. 

As **User**,

I want to get the links to the leagues of the NFL Fantasy game 
I want to get the link to the archives (which will exist until the season starts) of the NFL Fantasy game 

**Acceptance Criteria**

- `!fantasy` gives the links for the Fantasy Leagues 
- `!fantasy Archiv` gives the link for the Fantasy Archive

As **Fantasy-Manager** 

I want the possibility to give users the Fantasy-Role, as a fallback option for the self-management of user roles and to keep the NFL Game as simple as possible for the discord administration. **Is only necessary after the Bot manages the user roles** 
I want to set basic informations the bot tells the user when using `!fantasy`

**Acceptance Criteria**

- `!set role Fantasy user` (or whatever the user role management will look like) gives the fantasy role to the user
- `!fantasy set trade/lineup/waiver deadline` sets the date of the Trade Deadline once or weekly for the lineup changes or the waiver wires. (Game Feature)

**Additional Information** 

Setting up the possibility of a !fantasy command may give way to some funny and useful features in the future I don't know yet. As the Fantasy Game will start no sooner than August, it has low priority.

**Comment by KDanny41** [comment]
Add:
!fantasy danny

What Gecki says: "Danny is the undefeated trash talker!"

**Comment by gobo7793** [comment]
You mean: "Danny is the defeated trash talker!"

**Comment by Fluggs** [comment]
What does that deadline thingy do, what bot feature (proposed or existing) is it used for?

**Comment by KDanny41** [comment]
Its an ingame feature. You have varying deadlines in the game for trading or acquiring NFL Players before either it's impossible for the remaining season or this gameweek. 

It's used for information for fantasy players, you can compare it to the DSC deadline for signup and voting. So as an example, as fantasy player I type:

"!fantasy waiver deadline"

and Gecki says

"Die Waiver Deadline ist Dienstag, 12 Uhr!" or stuff like this.

**Comment by KDanny41** [comment]
Additional comment: Maybe the bot could say "The Waiver Deadline is now over!" automatically when the deadline the fantasy master set is over.

**Comment by KDanny41** [comment]
I'ma try to make this on my own so there's that

**Comment by gobo7793** [comment]
Implemented in 2.0, maybe there come future updates
