### ISSUE TITLE
Acquire roles via reactions

### ISSUE THREAD

**Issue by Lubadubs** [gobo7793/Geckarbot#18]
<h2>User stories</h2>
<ul>
<li>I, as a normal user, want to be able to get and delete non-specific roles via reacting to a bot message.</li>
<li>I, as a manager of a role, want to assign and delete other users the role I am manager of via a single bot command.</li>
</ul>

<h2>Requirement criteria</h2>
<ul>
<li>The bot will send an initial post and give predefined reactions to it.</li>
<li>If a user clicks on a reaction the bot should assign the user the respective role.</li>
<li>If a user clicks again on a reaction to remove the reaction the bot also should remove the respective role.</li>
<li>It's not possible to self-assign roles that are special roles.</li>
<li>Users with predefined master roles can use a bot command to assign roles to other users that correspond to the master role.</li>
</ul>

<h2>Reaction definitions</h2>
<table>
<tr><th>Role</th><th>Reaction</th></tr>
<tr><td>stellaris</td><td>:ringed_planet:</td></tr>
<tr><td>euiv</td><td>:flag_eu:</td></tr>
<tr><td>gta</td><td>:gun:</td></tr>
<tr><td>tippspiel</td><td>:dart:</td></tr>
</table>

<h2>Special roles</h2>
<table>
<tr><th>Area</th><th>User role</th><th>Manager role</th></tr>
<tr><td>minecracy</td><td>my</td><td>mymaster</td></tr>
<tr><td>nfl fantasy</td><td>fantasy</td><td>fantasymaster</td></tr>
<tr><td>dsc</td><td>songuser</td><td>songmaster</td></tr>
</table>

**Comment by gobo7793** [comment]
Manager roll for minecracy: my-mod
Fantasy may doesn't need a manager role

**Comment by gobo7793** [comment]
Now we have a new Role: Switch, Possible reaction: 🎮

**Comment by gobo7793** [comment]
## Concept Draft
Short: The bot should make the current existing role _rollenmaster_ needless and replace it
- The bot will send an initial post and give predefined reactions to it.
- If a user clicks on a reaction the bot should assign the user the respective role.
- If a user clicks again on a reaction to remove the reaction the bot also should remove the respective role.
- It's not possible to self-assign roles that are special roles.
- Users with predefined master roles can use a bot command to assign roles to other users that correspond to the master role.
- Some roles can be self-assigned and through predefined master roles.
- Self-assignable roles can be added or deleted via command
- After adding/deleting roles the initial post should be updated with its reactions
- Some really special roles can't be assign via bot and only via Admins

### Reactions
<table>
<tr><th>Role</th><th>Reaction</th></tr>
<tr><td>ttt</td><td>:elke:</td></tr>
<tr><td>stellaris</td><td>:ringed_planet:</td></tr>
<tr><td>euiv</td><td>:flag_eu:</td></tr>
<tr><td>gta</td><td>:gun:</td></tr>
<tr><td>tippspiel</td><td>:dart:</td></tr>
<tr><td>switch</td><td>:video_game:</td></tr>
<tr><td>songuser</td><td>:headphones:</td></tr>
</table>

### Special roles
<table>
<tr><th>Area</th><th>User role</th><th>Manager role</th></tr>
<tr><td>Bot development</td><td>botmaster</td><td>botmaster</td></tr>
<tr><td>Minecracy MP</td><td>my</td><td>my-mod</td></tr>
<tr><td>Fantasy Football</td><td>fantasy</td><td>fantasymaster</td></tr>
<tr><td>dsc</td><td>songuser</td><td>songmaster</td></tr>
</table>

### Roles not affected by bot
- Admin
- Techniker
- Bot
- Readonly
- User
- Modkandidat, if mod election in progress

### Manage role commands
- `!role <user> add <role>`: Assign role to user. Only usable for users with corresponding master role. Mods can use that for all roles.
- `!role <user> del <role>`: Remove role from user. only usable for users with corresponding master role. Mods can use that for all roles.
- `!role add <role> <emoji> <color>`: Create new self-assignable role. Mods only.
- `!role add <role> <color> <masterrole>`: Create a new role with corresponding master role. Mods only.
- `!role del <role>`: Delete role. Mods only.
