### ISSUE TITLE
Individual default config for plugins

### ISSUE THREAD

**Issue by gobo7793** [gobo7793/Geckarbot#41]
**What's your feature request? Please describe the user story.**
If no a plugin configuration can't be loaded, a default configuration will be setted. Currently it's an empty dictionary for all plugins. If a plugin has no configuration, it should get a individual default configuration.

**Describe the solution you'd like (acceptance criteria)**
Extend Plugin API and Config API that plugins can provide a default configuration if no configuration can be loaded. Possible implementation:
```
class Plugin():
  def get_default_config():
   return default_config

class Config():
  def load(plugin):
    if loaded is error:
      return plugin.get_default_config()
```

**Comment by Fluggs** [comment]
Alternatively, the Config API could return None or raise an Exception (would be cleaner) if it didn't find anything. The plugin can then decide what to do (such as use / set a default config).
