### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Fluggs** [gobo7793/Geckarbot#47]
As a server admin,
I want to update the bot
**because** new versions are cool.

**Acceptance criteria**
* New command: `!update [version]`
* Fetches the tagged version `version` from GitHub and restarts the bot.
* If `version` is omitted, the bot updates to the newest version available (if that version is not already running).
* The bot is allowed to shut down for this process.

**Comment by gobo7793** [comment]
Usage of this should be logged in admin channel, see #40

**Comment by gobo7793** [comment]
If I interpreted it correctly, it should not be in the misc plugin. Mod plugin would be better.

**Comment by Fluggs** [comment]
Merged in #54.
