### ISSUE TITLE
Add a feedback module for meta stuff

### ISSUE THREAD

**Issue by KDanny41** [gobo7793/Geckarbot#55]
as a **user**,
I want to be able to give feedback and complaints as well as be able to contribute in any way
because meta stuff is important.

## Acceptance criteria
* `!github` gives the following text: "https://github.com/gobo7793/Geckarbot - Ideen, Bugs und Vorschläge zum Bot sind immer gerne gesehen!" or any similar post. 
* `!about` lets the bot tell about itself
* `!complain` <text> saves feedback encoded in <text> either to github or to an internal storage.
* On `!complain`, the bot informs the user that their feedback has been stored.

If we go the internal storage route (github issues kinda suck because abusable and requires an acc):
* We need a good name for the following commands; I (fl) came up with `fanmail`or `redact`; not really happy with either.
* `!redact` reads new / all complaints in an enumerated fashion (important for delete). Ideally, the complaints contain a link to the original `complain` msg for context.
* `!redact delete #` deletes complaint #x.

**Comment by Fluggs** [comment]
Merged in #56.
