### ISSUE TITLE
Google Sheets API

### ISSUE THREAD

**Issue by gobo7793** [gobo7793/Geckarbot#61]
**What's your feature request? Please describe the user story.**
As Dev I want to
- interact with the Google Sheets API for various reasons (like #14 oder #15)

**Describe the solution you'd like (acceptance criteria)**
Easy accessing and using of Google Sheets API for Plugins

**Additional context or informations**
Google Sheets API doc: https://developers.google.com/sheets/api?hl=en

**Comment by Fluggs** [comment]
https://developers.google.com/sheets/api/reference/rest
They also have a rest api.

**Comment by gobo7793** [comment]
Note: Build a switch to disable usage of sheets API if using Google Client Library pip packages.

**Comment by gobo7793** [comment]
Current Implementation has only get method, todo: Write to sheets and batch get

**Comment by costamiri** [comment]
Get, batchGet, update and append implemented. Still missing: batchUpdate

**Comment by costamiri** [comment]
batchUpdate, findReplace, Duplicate, addSheet all implemented
