### ISSUE TITLE
Use general bot config for kwiss channel mapping

### ISSUE THREAD

**Issue by gobo7793** [gobo7793/Geckarbot#65]
In the attribute `jsonify` for the kwiss plugin there are some hard coded channel mappings. Better would be to use the general bots config for this channel mapping. For this, the channels has to be added to the general bot config and can securely tested on testservers.

Notable difference: In bot config the channel name are the key and the ID the value.

See https://github.com/gobo7793/Geckarbot/wiki/Plugin-and-Config-API#bot-system-configuration

**Comment by Fluggs** [comment]
#34 .
