### ISSUE TITLE
Bar plugin

### ISSUE THREAD

**Issue by gobo7793** [gobo7793/Geckarbot#93]
**What's your feature request? Please describe the user story.**
As user/dev I want to
- easy add and remove commands with simple outputs like `!mud` or `!nico` during runtime and w/o editing the source code
- adding cmds for every user, removing only for mods, maybe also for command creator
- commands must support wildcards for additional arguments for command

**Describe the solution you'd like (acceptance criteria)**
- implement a Bar plugin which alllows to create and remove such commands during runtime
- the commands and their output should be saved in a config file
- if a command creator can remove its own command, the user id must also be saved
- `!add <cmd_name> <text>` to add a command !cmd_name
- `!remove <cmd_name>` to remove command !cmd_name, only for mods and maybe the creator
- `!list` to list added command names
- Wildcards:
  - `%<int>` for arguments where <int> defines the number of the argument: %1 = !cmd arg1
  - `%u` user which uses the command
- Commands should be used with own prefix like `+<cmd_name>`, if possible

**Additional context or informations**
Commands must not violate the command guidelines (WIP, #91)

**Comment by Fluggs** [comment]
Not sure what this has to do with a bar

**Comment by gobo7793** [comment]
Kalles feature to add cmds called bar because he could give you some drinks via command
